"""Add card orb and uses

Revision ID: 5c488131a0ea
Revises: ef9611d1b9a7
Create Date: 2022-05-25 21:33:54.966996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c488131a0ea'
down_revision = 'ef9611d1b9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('card_orb', sa.Integer(), nullable=False, default=0))
    op.add_column('deck', sa.Column('card_num_uses', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck', 'card_num_uses')
    op.drop_column('deck', 'card_orb')
    # ### end Alembic commands ###
