"""Remove player life

Revision ID: ef9611d1b9a7
Revises: e12496c22d64
Create Date: 2022-04-03 23:40:23.015722

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ef9611d1b9a7'
down_revision = 'e12496c22d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'life')
    # ### end Alembic commands ###


# BEGIN TRANSACTION;
# CREATE TEMPORARY TABLE t1_backup(id,name,damage,powered_down,avatar_filename,instructions,will_power_down,active);
# INSERT INTO t1_backup SELECT id,name,damage,powered_down,avatar_filename,instructions,will_power_down,active FROM player;
# DROP TABLE player;
# CREATE TABLE player(id,name,damage,powered_down,avatar_filename,instructions,will_power_down,active);
# INSERT INTO player SELECT id,name,damage,powered_down,avatar_filename,instructions,will_power_down,active FROM t1_backup;
# DROP TABLE t1_backup;
# COMMIT;

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('life', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
